# Generated by Django 4.0.2 on 2022-02-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=7)),
                ('country', models.CharField(max_length=100)),
                ('countryCode', models.CharField(max_length=4)),
                ('region', models.CharField(max_length=50)),
                ('regionName', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.DecimalField(decimal_places=10, max_digits=100)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=100)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=100)),
                ('timezone', models.CharField(max_length=50)),
                ('isp', models.CharField(max_length=50)),
                ('org', models.CharField(max_length=50)),
                ('_as', models.CharField(max_length=250)),
                ('query', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Ip',
                'verbose_name_plural': 'Ips',
                'ordering': ['id'],
            },
        ),
    ]
