# Generated by Django 4.0.2 on 2022-02-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmodel',
            name='_as',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='ipmodel',
            name='org',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ipmodel',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ipmodel',
            name='regionName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ipmodel',
            name='zip',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100),
        ),
    ]
