# Generated by Django 4.0.2 on 2022-02-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ipmodel__as_alter_ipmodel_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmodel',
            name='zip',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=100),
        ),
    ]
