# Generated by Django 4.0.2 on 2022-02-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ipmodel_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmodel',
            name='isp',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ipmodel',
            name='org',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='ipmodel',
            name='zip',
            field=models.DecimalField(decimal_places=10, max_digits=100, null=True),
        ),
    ]
